export const productData = [
    {
      id: 1,
      name: "UNISEX OVER SIZED TEE - BLACK",
      maninimage: '/images/Black-Tshirt.png',
      offerprice: 'Rs. 1,200.00',
      originalprice: 'Rs. 2,000.00',
      oldPricepoint: 2000,
      newPricepoint: 1200,
      sold: "1,238",
      rating: 4.5,
      quantity: 1,
      tags: ["tshirt", "tee", "tees", "oversized", "black", "unisex", "cotton", "casual"],
      description:
        "Simplicity meets style in this versatile unisex t-shirt, designed with a clean, comfortable fit and a focus on the back for standout prints or graphics. Made from soft, breathable cotton, this tee offers all-day comfort for any occasion.",
      color: "Black",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/cloth-details-1.png",
        "/images/cloth-details-2.png",
        "/images/cloth-details-3.png",
        "/images/cloth-details-4.png",
        "/images/cloth-details-5.png",
      ],
    },
    {
      id: 2,
      name: 'UNISEX OVER SIZED TEE - BEIGE',
      maninimage: '/images/Beige-Tshirt.png',
      offerprice: 'Rs. 1,500.00',
      originalprice: 'Rs. 2,000.00',
      oldPricepoint: 2000,
      newPricepoint: 1500,
      sold: "1,005",
      rating: 4.5,
      quantity: 1,
      tags: ["tshirt", "tee", "tees", "oversized", "beige", "unisex", "cotton", "casual"],
      description:
        "This beige unisex t-shirt brings understated style to your wardrobe. Designed with a relaxed, modern fit and crafted from soft, breathable cotton, it offers lasting comfort from day to night.",
      color: "Beige",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/Beige-cloth-details-1.png",
        "/images/Beige-cloth-details-2.png",
        "/images/Beige-cloth-details-3.png",
        "/images/Beige-cloth-details-4.png",
        "/images/Beige-cloth-details-5.png",
      ],
    },
    {
      id: 3,
      name: 'UNISEX OVER SIZED TEE - PINK',
      maninimage: '/images/PearlPink-Tshirt.png',
      offerprice: 'Rs. 1,600.00',
      originalprice: 'Rs. 2,000.00',
      oldPricepoint: 2000,
      newPricepoint: 1600,
      sold: "900",
      rating: 4.4,
      quantity: 1,
      tags: ["tshirt", "tee", "tees", "oversized", "pink", "unisex", "cotton", "casual"],
      description:
        "Add a pop of personality with this pink unisex t-shirt. Its gentle hue balances playful energy with a timeless cut, made to stand out without trying too hard. Made from premium cotton for a breathable, all-day fit.",
      color: "PINK",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/Pink-cloth-details-1.jpeg",
        "/images/Pink-cloth-details-2.jpeg",
        "/images/Pink-cloth-details-3.png",
        "/images/Pink-cloth-details-4.png",
        "/images/Pink-cloth-details-5.jpg",
      ],
    },
    {
      id: 7,
      name: 'FANDOM UNISEX BLACK SHORTS',
      maninimage: '/images/shorts-black.png',
      offerprice: 'Rs. 1,600.00',
      originalprice: 'Rs. 2,600.00',
      oldPricepoint: 2600,
      newPricepoint: 1600,
      sold: "1112",
      rating: 4.4,
      quantity: 1,
      tags: ["pant", "pants", "shorts", "black", "unisex", "cotton", "casual"],
      description:
        "Command effortless style in these black unisex shorts their sleek silhouette brings understated confidence, combining everyday comfort with sharp, minimalist edge. Crafted from breathable cotton for all-day ease—versatile, timeless, and built to move with you.",
      color: "PINK",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/shorts-black-details-1.png",
        "/images/shorts-black-details-2.png",
        "/images/shorts-black-details-3.png",
        "/images/shorts-black-details-4.png",
        "/images/shorts-black-details-5.png",
      ],
    },
    {
      id: 8,
      name: 'FANDOM UNISEX GREY SHORTS',
      maninimage: '/images/shorts-grey.png',
      offerprice: 'Rs. 1,600.00',
      originalprice: 'Rs. 2,600.00',
      oldPricepoint: 2600,
      newPricepoint: 1600,
      sold: "1103",
      rating: 4.5,
      quantity: 1,
      tags: ["pant", "pants", "shorts", "grey", "unisex", "cotton", "casual"],
      description:
        "Redefine relaxed style with these grey cotton shorts. Soft, breathable, and endlessly versatile—their neutral hue pairs effortlessly with any look. Designed for everyday movement with a tailored fit that feels as good as it looks. Casual comfort, elevated.",
      color: "PINK",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/shorts-grey-details-1.png",
        "/images/shorts-grey-details-2.png",
        "/images/shorts-grey-details-3.png",
        "/images/shorts-grey-details-4.png",
        "/images/shorts-grey-details-5.png",
      ],
    },
    {
      id: 9,
      name: 'FANDOM UNISEX DENIM SHORTS',
      maninimage: '/images/shorts-denim.png',
      offerprice: 'Rs. 1,200.00',
      originalprice: 'Rs. 2,000.00',
      oldPricepoint: 2000,
      newPricepoint: 1200,
      sold: "1127",
      rating: 4.5,
      quantity: 1,
      tags: ["pant", "pants", "shorts", "denim", "unisex", "jeans", "casual"],
      description:
        "Redefine relaxed style with these grey cotton shorts. Soft, breathable, and endlessly versatile—their neutral hue pairs effortlessly with any look. Designed for everyday movement with a tailored fit that feels as good as it looks. Casual comfort, elevated.",
      color: "DENIM",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/shorts-denim-details-1.png",
        "/images/shorts-denim-details-2.png",
        "/images/shorts-denim-details-3.png",
        "/images/shorts-denim-details-4.png",
        "/images/shorts-denim-details-5.png",
      ],
    },
    {
      id: 10,
      name: 'FANDOM UNISEX GREEN SHORTS',
      maninimage: '/images/shorts-green.png',
      offerprice: 'Rs. 1,200.00',
      originalprice: 'Rs. 2,000.00',
      oldPricepoint: 2000,
      newPricepoint: 1200,
      sold: "1127",
      quantity: 1,
      rating: 4.5,
      tags: ["pant", "pants", "shorts", "green", "unisex", "jeans", "casual"],
      description:
        "Redefine relaxed style with these green cotton shorts. Soft, breathable, and endlessly versatile—their neutral hue pairs effortlessly with any look. Designed for everyday movement with a tailored fit that feels as good as it looks. Casual comfort, elevated.",
      color: "GREEN",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/shorts-green-details-1.png",
        "/images/shorts-green-details-2.png",
        "/images/shorts-green-details-3.png",
        "/images/shorts-green-details-4.png",
      ],
    },
    {
      id: 11,
      name: 'FANDOM UNISEX PINK SHORTS',
      maninimage: '/images/shorts-pink.png',
      offerprice: 'Rs. 3,200.00',
      originalprice: 'Rs. 4,000.00',
      oldPricepoint: 4000,
      newPricepoint: 3200,
      sold: "1127",
      rating: 4.5,
      quantity: 1,
      tags: ["pant", "pants", "shorts", "pink", "unisex", "cotton", "casual"],
      description:
        "Redefine relaxed style with these pink cotton shorts. Soft, breathable, and endlessly versatile—their neutral hue pairs effortlessly with any look. Designed for everyday movement with a tailored fit that feels as good as it looks. Casual comfort, elevated.",
      color: "PINK",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/shorts-pink-details-1.png",
        "/images/shorts-pink-details-2.png",
        "/images/shorts-pink-details-3.png",
        "/images/shorts-pink-details-4.png",
        "/images/shorts-pink-details-5.png",
      ],
    },
    {
      id: 12,
      name: 'FANDOM UNISEX Pink SHORTS',
      maninimage: '/images/shorts-blue.png',
      offerprice: 'Rs. 3,200.00',
      originalprice: 'Rs. 4,000.00',
      oldPricepoint: 2000,
      newPricepoint: 1200,
      sold: "1127",
      rating: 4.5,
      description:
        "Redefine relaxed style with these grey cotton shorts. Soft, breathable, and endlessly versatile—their neutral hue pairs effortlessly with any look. Designed for everyday movement with a tailored fit that feels as good as it looks. Casual comfort, elevated.",
      color: "PINK",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
      images: [
        "/images/shorts-blue-details-1.jpg",
        "/images/shorts-blue-details-2.jpg",
        "/images/shorts-blue-details-3.jpg",
        "/images/shorts-blue-details-4.jpg",
        "/images/shorts-blue-details-5.jpg",
      ],
    },
    {
      id: 13,
      name: 'UNISEX BLACK CAP',
      maninimage: '/images/capmain.png',
      offerprice: 'Rs. 1,100.00',
      originalprice: 'Rs. 1,800.00',
      oldPricepoint: 1800,
      newPricepoint: 1100,
      sold: "1127",
      rating: 4.5,
      quantity: 1,
      tags: ["cap", "head cap", "sun protector", "black cap", "black", "unisex"],
      description:
        "This unisex black cap is more than just a finishing touch — it’s a statement of effortless style. With a sleek silhouette and classic fit, it blends into any wardrobe while standing out in the details. Whether you're shielding from the sun or adding edge to your everyday look",
      color: "bLACK",
      sizes: ["FREE"],
      images: [
        "/images/cap1.jpeg",
        "/images/cap2.jpeg",
        "/images/cap3.jpeg",
        "/images/cap5.jpeg",
      ],
    },
    {
      id: 14,
      name: 'FANDOM UNISEX BROWN BELT',
      maninimage: '/images/beltbrownmain.png',
      offerprice: 'Rs. 900.00',
      originalprice: 'Rs. 1,200.00',
      oldPricepoint: 1200,
      newPricepoint: 900,
      sold: "1007",
      rating: 4.5,
      quantity: 1,
      tags: ["belt", "waist belt", "sun protector", "brown belt", "brown", "unisex"],
      description:
        "A timeless essential that ties every look together. Crafted for both function and finesse, this belt balances classic design with everyday durability.",
      color: "BROWN",
      sizes: ["FREE"],
      images: [
        "/images/beltbrown2.jpg",
        "/images/beltbrow1.jpg",
        "/images/beltbrown3.jpg",
        "/images/beltbrown5.jpg",
      ],
    },
    {
      id: 15,
      name: 'FANDOM WOMEN BEIGE BAG',
      maninimage: '/images/beigebag.png',
      offerprice: 'Rs. 2,000.00',
      originalprice: 'Rs. 2,500.00',
      oldPricepoint: 2500,
      newPricepoint: 2000,
      sold: "1007",
      rating: 4.5,
      quantity: 1,
      tags: ["beige", "shoulder bag", "satchel", "beige bag", "bag", "women bag"],
      description:
        "Soft in hue, bold in presence — this beige bag is a modern classic designed to move with you. From casual brunches to evening outings, its neutral tone pairs effortlessly with any look while the structured silhouette keeps things polished. Elegance, redefined for the everyday",
      color: "BEIGE",
      sizes: ["FREE"],
      images: [
        "/images/beigebag4.jpg",
        "/images/beigebag5.jpg",
        "/images/beigebag3.jpg",
        "/images/beigebag2.jpg",
      ],
    },
  ];
  